### ISSUE TITLE
Randomize job log name

### ISSUE THREAD

**Issue by l-althueser** [XENONnT/env_starter#13]
If one want to start more than one job for testing different container if would be handy to have various log files.

**Comment by ershockley** [comment]
@l-althueser do you think it would suffice to  make a script for normal batch jobs instead of notebook jobs for such tests? I think it is not ideal for users to have multiple notebook jobs running

**Comment by l-althueser** [comment]
We do not stop user from having multiple jobs by redirecting to only one log file right now. I experienced quite some analysts that just know about one job (because one log file) but actually had many running.
I usually work with one montecarlo Jupyter and one straxen jupyter to work on two different tasks at the same time. So I think there are valid use cases but maybe we could only allow that when someone adds the force_new keyword .. so that for normal user all is the same. What do you think?

**Comment by ershockley** [comment]
Yeah I've definitely noticed this in the past and usually try to call out people. But people should anyway be checking the job queue to see if they have job(s) running, not log files.

I thought that having a single log file would help simplify where to look for e.g. ssh tunneling information since it's always in the same place, unlike the tmp files that we used to use. 

I can partially see the use case of having a notebook for MC_env and base_env, but part of me still thinks this is a non-ideal use of resources since you cannot be actively working on both at the same time right? Since these are shared resources I think it is not a great precedent to set. But we can consider naming logs for each environment maybe?

**Comment by l-althueser** [comment]
We should definitely not have multiple Jupyter jobs running. This is more for when you are working on something but want to do a 5-10min check or test with cutax versions to see the result. Afterwards deleting the job again but continuing on the original one. Sometime now two jobs are writing to one file and everything gets a bit messy then. Although there are many other ways to do this - this is just very convenient to test from the eyes of analysts.

**Comment by ershockley** [comment]
Yeah I guess where I'm coming from Lutz is that I think the benefits of having a single place for the log file outweigh the gain we get to do these 10 minute checks. For those checks can we instead have people do interactive jobs or submit test batch jobs to the normal batch queue? Starting up these jupyter jobs that last for 8 hours if not removed manually doesn't seem the best way to do these types of things, in my view at least. 

That being said, happy to review+merge a PR if you have something in mind. (maybe make a `notebook_2.log` if a job already exists? idk).
